### ISSUE TITLE
Wink status not updating

### ISSUE THREAD

**Issue by jsg4** [home-assistant/home-assistant.io#562] opened 2016-06-16 13:00 UTC
Just wondering if anyone has any issues with Wink status for switches/lights not updating in Home Assistant since a week ago? I tried a new refreshed API key and still not seeing status. I can control devices, but no status.

**Comment by balloob** [comment] 2016-06-16 15:34
This is for issues on the website. Please report in the main repo. It's probably a duplicate of https://github.com/home-assistant/home-assistant/issues/2314

**Closed by balloob** 2016-06-16 15:34 UTC
